package controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import dao.ReportsDAO;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Report;

@WebServlet("/ExportPDFServlet")
public class ExportPDFServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request,
                         HttpServletResponse response)
            throws ServletException, IOException {

        ReportsDAO dao = new ReportsDAO();
        Report report = dao.getDashboardReport();

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition",
                "attachment; filename=Sunrise_Dental_Report.pdf");

        try {

            Document document = new Document();

            PdfWriter.getInstance(document, response.getOutputStream());

            document.open();

            Font titleFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 20);

            Font headingFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD, 14);

            Font normalFont = FontFactory.getFont(
                    FontFactory.HELVETICA, 12);

            document.add(new Paragraph(
                    "SUNRISE DENTAL CLINIC", titleFont));

            document.add(new Paragraph(
                    "Management System Report", headingFont));

            document.add(new Paragraph(" "));

            document.add(new Paragraph(
                    "Generated Date : "
                    + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
                            .format(new Date()),
                    normalFont));

            document.add(new Paragraph(
                    "------------------------------------------------------"));

            document.add(new Paragraph(
                    "Total Patients : "
                            + report.getTotalPatients(),
                    normalFont));

            document.add(new Paragraph(
                    "Total Appointments : "
                            + report.getTotalAppointments(),
                    normalFont));

            document.add(new Paragraph(
                    "Total Treatments : "
                            + report.getTotalTreatments(),
                    normalFont));

            document.add(new Paragraph(
                    "Paid Bills : "
                            + report.getPaidBills(),
                    normalFont));

            document.add(new Paragraph(
                    "Pending Bills : "
                            + report.getPendingBills(),
                    normalFont));

            document.add(new Paragraph(
                    "Total Revenue : Rs. "
                            + String.format("%,.2f",
                                    report.getTotalRevenue()),
                    normalFont));

            document.add(new Paragraph(
                    "------------------------------------------------------"));

            document.add(new Paragraph(" "));
            document.add(new Paragraph(
                    "Generated by Sunrise Dental Clinic Management System",
                    headingFont));

            document.close();

        } catch (Exception e) {

            throw new ServletException(e);

        }

    }
}